version: "3"
services:
  mongodb:
    image: mongo:6.0
    container_name: cat-mongodb
    restart: unless-stopped
    ports:
      - 27017:27017
    volumes:
      - mongo_data:/data/db

volumes:
  mongo_data:
# docker-compose up -d
# mongosh mongodb://localhost:27017
